# Generated by Django 4.2.8 on 2023-12-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_options_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default_product.webp', upload_to='products/products/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
